import {Event} from './event-interface';

export const events: Event[] = [
    {_id:"1",sport:"Athletics",rulebook:'https://rb.gy/ty6zds',images:'athletics.png',description:"With every new day comes a unique opportunity, IIT Bombay is here to welcome you to its sports fest, Aavhan from the 24th - the 26th of March, giving you a chance to embrace your inner Athletic spirit, serving as an anchor to greater and new beginnings. If you're looking for information concerning any athletic activities at Aavhan, you have come to the right place, our page will keep you updated regarding all the track and field events. I hope our page serves you well and motivates your inner athletic spirit. To New Beginnings & Warm Memories!!",date:"24th-26th March"},
    {_id:"2",sport:"Badminton",rulebook:'https://rb.gy/dycuiz',images:'badminton.png',description:"With multiple indoor and outdoor courts, here's your opportunity to play at IIT Bombay from 24th to 26th March. It's time to make every shot count at Aavhan this year. With overall 7 different categories in total in mens, womens and 30+ mens category, amazing cash prizes are waiting for you. What are you waiting for? The clock's ticking, so sign your team up quickly.",date:'24th-26th March'},
    {_id:"3",sport:"Basketball",rulebook:'https://rb.gy/jwzxj1',images:'basketball.png',description:"With multiple indoor and outdoor courts, here's your opportunity to play at IIT Bombay from 24th to 26th March. It's time to make every shot count at Aavhan this year. So what are you waiting for? The clock's ticking, so sign your team up quickly.",date:'23rd-26th March'},
    {_id:"4",sport:"Chess",rulebook:'https://rb.gy/qhzyqm',images:'chess.png',description:"Aavhan Chess 2023 promises to be a spectacle with a prize fund of over INR 2.2 Lakh along with trophies in various categories, so get ready to be a part of this exhibition with some of the best minds in the country as they battle it out over the 64 squares. Chess would consist of an open Rapid tournament as well as a Blitz exhibition event, so register now on the Aavhan website and see you over the board on 25th and 26th March!",date:'25th-26th March'},
    {_id:"5",sport:"Cricket",rulebook:'https://rb.gy/21ygev',images:'cricket.png',description:"Mark your calendars, for Aavhan 2023 is here from 24th to 26th March! Limited registrations, so register fast and get a chance to compete against some of the best college cricket teams of the country. Exciting prizes await!",date:'20th-26th March'},
    {_id:"6",sport:"Football",rulebook:'https://rb.gy/dt26tb',images:'football.png',description:"Attention to all the footballers out there as we present to you the Aavhan's football fiesta. Here at Aavhan IIT Bombay, we provide a platform for young and talented players to showcase their skills and compete with some of the best football teams in the country. So join us in this festival of football and enjoy the thrills and last minute dramas as the teams battle it out to be crowned as the Aavhan Football Champions.",date:'20th-26th March'},
    {_id:"7",sport:"Hockey",rulebook:'https://rb.gy/iuecsg',images:'hockey.png',description:"Attention all hockey enthusiasts!We are excited to announce our upcoming sports fest - Aavhan.Join us for an action-packed event with top hockey teams from around the region. Hockey is a game of speed, strategy,and teamwork. It's a sport that requires you to be constantly on your toes , both physically and mentally .Mark your calendars and get ready to cheer on your favorites. Let the games begin!",date:'24th-26th March'},
    {_id:"8",sport:"Kabaddi",rulebook:'https://rb.gy/ntjv83',images:'kabaddi.png',description:"Kabaddi promises to be an exciting and competitive sport to be played on the indoor court in Aavhan 2023, showcasing the strength, agility, and tactical abilities of the players. The Kabaddi game will be played on the synthetic mat in the league format. For the first time ever Aavhan is conducting a girls' Kabaddi match. So boys and girls get ready on 23rd March to show your skills, and your ability to hit the bonus. See you on the court",date:'23rd-26th March'},
    {_id:"9",sport:"Kho Kho",rulebook:'https://rb.gy/1jfdeq',images:'khokho.png',description:"Be a part of Aavhan to experience a thrilling game that demands quick reflexes and communication. It'll be conducted on none other than the perfect Kho Kho indoor court, a synthetic mat to give players a professional feel. The match will be conducted in league format. Be prepared from 23rd March with your agility, speed, and strategic teamwork. Mat the best team win!",date:'23rd-26th March'},
    {_id:"10",sport:"Lawn Tennis",rulebook:'https://rb.gy/vh5gcn',images:'lawntennis.png',description:'IIT Bombay boasts most number of tennis courts in a single location with 6 synthetic tennis courts. We take the pleasure to invite you all to Aavhan 2023 from 24th to 26th March 2023 to share this ground with us and teams from all over India. Let’s cheer to the sportsmanship in the gentleman’s game. Hoping to see you here!',date:'24th-26th March'},
    {_id:"11",sport:"Powerlifting",rulebook:'https://rb.gy/n7gkya',images:'powerlifting.png',description:"Prepared to set new PRs? The stage is ready for you with our Powerlifting event at Aavhan. So set your calendars to the 25th and 26th March, hit the gym, and of course, register quickly!",date:'24th-26th March'},
    {_id:"12",sport:"Squash",rulebook:'https://rb.gy/tszhbu',images:'squash.png',description:"Get ready to play at IIT Bombay's finest indoor courts from 24th to 26th March as the Aavhan Squash Championship aims to bring in some of the best players from Mumbai and across the country. With 3 formats including Men's team, men's singles and women's singles, it's time to show your skills on the courts and stand a chance to win exciting prizes! Go ahead and register now as limited seats are available.",date:'24th-26th March'},
    {_id:"13",sport:"Swimming",rulebook:'https://rb.gy/mpfzca',images:'swimming.png',description:"With over 15 events in various categories along with Water Polo in a state of the art swimming pool, Aavhan 2023 promises to be a worthwhile experience for all its swimmers. Be prepared from 24-26 March, put your swimming caps on and set new records. Registrations are limited so what are you waiting for! Go register on the Aavhan website, exciting prizes await.",date:'24th-26th March'},
    {_id:"14",sport:"Table Tennis",rulebook:'https://rb.gy/knez62',images:'tabletennis.png',description:"Get ready to participate in the fiercest tournament of the year as we bring to you the table tennis tournament in Aavhan this year. We are hosting three categories for table tennis - men’s singles, men’s team and women’s singles. Only the most skilled and seasoned player will emerge victorious. So gather your racquets and sharpen your skills. I wish you all the very best for the epic showdown at the table.May the best player win.",date:'24th-26th March'},
    {_id:"15",sport:"Ultimate Frisbee",rulebook:'https://rb.gy/mvzl1x',images:'frisbee.png',description:'Ultimate Frisbee is a beautiful sport and an amazing community. Some of the best college Ultimate teams in India are on their way to be a part of Aavhan and you don’t want to miss this!Registrations are OPEN for Aavhan 2023!',date:'23rd-26th March'},
    {_id:"16",sport:"Volleyball",rulebook:'https://rb.gy/nqt4b0',images:'volleyball.png',description:"Be a part of Aavhan this year from 24-26 March, where the spirit of spiking and service lives on! With some of India's top-notch indoor volleyball courts, you'll regret missing out. Limited registrations are available for men's and women's teams!",date:'24th-26th March'},
    {_id:"17",sport:"Wall Climbing",rulebook:'https://rb.gy/z6r5fp',images:'wallclimbing.png',description:'Bouldering is a type of rock climbing which is done without the use of a harness. The equipment used by the climbers are climbing shoes, chalk to keep their hands dry, and bouldering mats to avoid injuries. Bouldering competitions can either be outdoor or indoor. In indoor competitions, the format has three rounds: the qualifications, semi-finals, and finals. Each round has different sets of boulder problems, and the climbers have a certain amount of time to attempt each problems. At the end, the climbers are ranked according to the problems they have completed. In other competitions, the climbers are given a fixed number of attempts for each problem, the time rests between each attempt. In other formats, they are only given the allotted time to fix the problem. In open-format competitions, the climbers compete at the same time. They are given a certain amount of time to complete as many problems as they can.',date:'25th-26th March'},
    {_id:"18",sport:"Water Polo",rulebook:'https://rb.gy/wpmcwy',images:'waterpolo.png',description:"With over 15 events in various categories along with Water Polo in a state of the art swimming pool, Aavhan 2023 promises to be a worthwhile experience for all its swimmers. Be prepared from 24-26 March, put your swimming caps on and set new records. Registrations are limited so what are you waiting for! Go register on the Aavhan website, exciting prizes await.",date:'24th-26th March'},
    {_id:"19",sport:"Weightlifting",rulebook:'https://rb.gy/m11dfx',images:'weightlifting.png',description:"We hope you have been finessing your technique and building your strength, for we are all set for you at Aavhan. Flaunt your strength at our Weightlifting event on 24th March. Time's running out though, so sign up soon!",date:'24th-26th March'},

]

